### ISSUE TITLE
Allow to choose redshift schema

### ISSUE THREAD

**Issue by gepser** [uswitch/bqshift#11]
I am able to run `bqshift` against public schema (by default) but I don't see any way to choose any other Postgres schema. I only can choose the `database` and the `table`, and by default, it asumes that table is located on the `public` schema, it is possible to change it?

**Comment by DanielSAndrade** [comment]
@gepser   I have a branch on my fork with that option:
https://github.com/DanielSAndrade/bqshift/tree/search_path

**Comment by gepser** [comment]
Thank you for this. I tried to use it but didn't `build`, maybe I did something wrong.

But in the end, I was using [segment](https://segment.com/) and I think segment handle the migration better than myself so, for now, I don't need to do anything else.

Thank you @DanielSAndrade
