### ISSUE TITLE
Cannot unload to S3..

### ISSUE THREAD

**Issue by nantani** [uswitch/bqshift#8]
I got these errors when I tried..
The table name is right. but It seems something wrong..

Do you have any idea?

2017/04/18 19:14:55 unloading to s3 2017/04/18 19:14:55 error unloading: pq: syntax error at or near "FROM"

**Comment by bbriggs** [comment]
It me, right now: https://xkcd.com/979/

But for real, did you figure this out? I'm hitting the same error
